DROP TABLE IF EXISTS CEP;
DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE CEP(
	ID INT NOT NULL AUTO_INCREMENT,
	STREET TEXT NOT NULL,
	DISTRICT VARCHAR(255),
	CITY TEXT NOT NULL,
	STATE VARCHAR(2) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ADDRESS(
	ID INT NOT NULL  AUTO_INCREMENT,
	CEP_ID INT NOT NULL,
	NUMBER INT NOT NULL,
	COMPLEMENT VARCHAR(255),
	PRIMARY KEY (ID),
	FOREIGN KEY(CEP_ID) REFERENCES CEP(ID)
);