DROP TABLE IF EXISTS CEP;

CREATE TABLE CEP(
	ID INT NOT NULL AUTO_INCREMENT,
	STREET TEXT NOT NULL,
	DISTRICT VARCHAR(255),
	CITY TEXT NOT NULL,
	STATE VARCHAR(2) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	PRIMARY KEY(ID)
);