INSERT INTO ADDRESS (CEP_ID, NUMBER, COMPLEMENT) VALUES (1, 287, 'conjunto 161');
INSERT INTO ADDRESS (CEP_ID, NUMBER, COMPLEMENT) VALUES (1, 604, null);
INSERT INTO ADDRESS (CEP_ID, NUMBER, COMPLEMENT)  VALUES (2, 513, 'cj. 65');
INSERT INTO ADDRESS (CEP_ID, NUMBER, COMPLEMENT)  VALUES (3, 1000, null);