DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE ADDRESS(
	ID INT NOT NULL  AUTO_INCREMENT,
	CEP_ID INT NOT NULL,
	NUMBER INT NOT NULL,
	COMPLEMENT VARCHAR(255),
	PRIMARY KEY (ID),
	FOREIGN KEY(CEP_ID) REFERENCES CEP(ID)
);